# Intro to Classification with Logistic Regression

<a id="object"></a>

## Learning Objectives

1. First, you'll be introduced to [Classification](#class) which is the other half of Supervised Learning. We'll explore the second ML algorithm of [Logistic Regression](#logreg) which is the Classification equivalent of Linear Regression.

2. During the process, we'll solve a classification problem regarding [Customer Churn](#churn). You'll practice a few exercises to clean and prepare the data for modeling.

2. You'll get a brief introduction to [Hyperparameters](#params), before diving into classification's [Evaluation Metrics](#metrics). This includes the [Confusion Matrix](#matrix) and the [Classification Report](#class_rep)

3. Last, we'll dive into a common classification issue known as [Class Imbalance](#imbalance). We'll look at how the default **Accuracy** measure is misleading and focus on other Evaluation Metrics such as the [F1 Score](#f1), [ROC-AUC Score](#rocauc), and [PR-AUC Score](#prauc).

4. The more refined & detailed list of learning outcomes can be found in the [Summary of Learning Outcomes](#summary) section at the end of the notebook.

<a id="recap"></a>

## Roadmap

- This section is just a quick review of where we are on our modeling roadmap
- **DISCUSSION/QUESTIONS**
    - What is the difference between Supervised Learning and Unsupervised Learning?
    - What is the difference between Regression and Classification?
    - Put simply, what is Linear Regression?
        - Where does it fall under the Supervised vs Unsupervised Learning category?
        - Is it a Regression or a Classification algorithm?
        - Why do you think we learned that one first?

<details>

<summary>Click Me: Hint!</summary>
<figure>
  <img src='img/ml_cheat_sheet.png'/>
  <figcaption>Image from <a href='https://blogs.sas.com/content/subconsciousmusings/files/2017/04/machine-learning-cheet-sheet.png'>KDNuggets - Which ML Algorithm should I use?</a></figcaption>
</figure>
</details>

<a id="class"></a>

## Intro to Classification

- Classification → ML that aims to predict categories
  - Example of "Spam" or "Not Spam"

<figure>
  <img src='img/class1.png'/>
  <figcaption>Image from <a href='https://blog.finxter.com/supervised-and-unsupervised-machine-learning/#%E2%9C%A8_Regression'>Finxster</a></figcaption>
</figure>

### Intro to Logistic Regression

- Similar to Linear Regression, Logistic Regression is a popular, quick, and simple ML algorithm
- Like Linear Regression, Logistic Regression uses a set of independent variables (x) to predict an outcome (y)
      
<details>
<summary>Click here for a visual linear vs logistic comparison</summary>

<figure>
  <img src='img/linlog.png' width='60%'/>
  <figcaption>Image from <a href='https://www.javatpoint.com/linear-regression-vs-logistic-regression-in-machine-learning'>Javatpoint</a></figcaption>
</figure>
</details>

- Linear Regression → predict a continuous value (ex. weight)
- Logistic Regression has only two possible outcomes for y: 0 or 1
    - Often as "classes"
- Examples of this include:
    1. a phone-text classifier to tell us if an incoming text should be marked "spam" or "not spam"
    2. radiological images to predict whether a tumor is benign or malignant
    3. Review credit history to predict whether a customer will default on their loan repayments or repay the loan
    4. Predicting if an anonymous data scientist will get a date... (yes or no)
- Logistic Regression to predict membership to a certain category
- A few business use-cases include:
    1. Qualify Leads: Used to segment users into distincit categories for business intelligence
        - ex. Which Dockers email subscribers will convert into buyers
        - With this information, one could streamline sales operations to focus on prospects who have the higher likelihood of buying
    2. Recommend Products (especially useful for digital businesses)
    - For instance, calculate the likelihood (probability) of a customer purchasing a brand new line of Levi's jeans
        - Range from 0 to 1 for 0 to 100% chance of occurence
    - If the likelihood of a customer buying these new jeans is greater than a certain threshold (for example, 80%), recommend the product for upselling on the website.
    - This increases overall sales because we're recommending products that are more likely to be purchased
- Advantages of Logistic Regression for deployment
    1. Ease of use
        - Like Linear Regression, training and maintaining the model has less engineering overheard than more complex models
    2. Interpretability
        - Logistic regression is relatively straightforward to interpret
        - Model can help us assess which input variable is responsible for the greatest change in predicted value
    3. Scalability
        - Algorithm is very efficient
        - Trains faster than other models
        - Easier to scale with a larger volume increase
    4. Real-time predictions
        - Because of the low engineering overhead, model can be retrained and generate predictions in near real-time

<a id="formula"></a>

### Comparing Linear vs Logistic on a Classification Dataset

- Imagine that we have a table for the number of late payments made by a customer (x) and 
- whether the customer later defaulted on their loan (y)
- Note: Not defaulted = 0 and Defaulted = 1

<figure>
  <img src='img/tabl_logreg_ex.png' width='50%'/>
  <figcaption>Image from <a href='https://www.keboola.com/blog/logistic-regression-machine-learning'>Keboola</a></figcaption>
</figure>

<a id="linreg"></a>

##### Linear Regression

- First, let's model the data using Linear Regression:
- Result would be a **straight line** that 'best' passes through the data points
- This is what the model would look like:
- The "red" and "blue" points on the graph represent customers who either defaulted (y = 1) or did not default (y = 0)

<figure>
  <img src='img/linreg_logreg_ex.png' width='50%'/>
  <figcaption>Image from <a href='https://www.keboola.com/blog/logistic-regression-machine-learning'>Keboola</a></figcaption>
</figure>

- Intuitively, does it look like the line fits the data points?
- Linear regression predicts probabilities outside the 0-1 (yes-no) range. 
    - Look at the regression line
    - It doesn't make sense for someone to have a negative 140% probability of default
- Look at the points where x = 2
    - Notice that it's unclear if we should categorize them under non-defaulting or defaulting behavior
- Let's try this now with Logistic Regression:

##### With Logistic Regression

<figure>
  <img src='img/logreg_logreg_ex.png' width='50%'/>
  <figcaption>Image from <a href='https://www.keboola.com/blog/logistic-regression-machine-learning'>Keboola</a></figcaption>
</figure>

- As you can see, it is no longer a straight line but an S-shaped curve
- Some data points are closer to either ends (near 0 and 1) of the line
- Does not go beyond the range of values (0 and 1)

### Logistic Formula

<details>
<summary>Click Me: Logistic Regression Formula</summary>

<figure>
  <img src='img/logreg_form.png' width='50%'/>
  <figcaption>Image from <a href='https://www.keboola.com/blog/logistic-regression-machine-learning'>Keboola</a></figcaption>
</figure>
</details>

- What you'll notice is that it looks way more complicated than the Linear Regression formula
- Just remember that the right side of the equation is used to predict "y"
- Like how `y = mx + b` is called the line equation and translates to a straight line, this is called the **sigmoid** function, which translates to the bounded *S*-shaped curve

<figure>
  <img src='img/logreg_logreg_ex.png' width='50%'/>
  <figcaption>Image from <a href='https://www.keboola.com/blog/logistic-regression-machine-learning'>Keboola</a></figcaption>
</figure>

### How Do We Classify?

- We have the same issue as we did with Linear Regression. How do we classify these points?
- Logistic Regression uses what's called a **Decision Boundary**
    - It's a threshold that's used to categorize the probabilities into discrete classes. For e.g. if we set 0.5 as a threshold
    - `y = 0 if predicted probability < 0.5`
        - A customer is not predicted to default if the probability of them defaulting is less than 50%<br><br>
    - `y = 1 if predicted probability is > 0.5`
        - A customer is predicted to default if the probability of them defaulting is greater than 50%

<a id="churn"></a>

## Introducing the Customer Churn Dataset

- We'll use the example of customer churn to explore binary classification using Logistic Regression 
    - Contains multiple features that could influence customer churn
- Popular [Telco Customer Churn](https://www.kaggle.com/blastchar/telco-customer-churn) dataset and here is some basic information from the Kaggle website:

<figure>
  <img src='img/churn_desc.png' width='70%'/>
  <figcaption>Image from <a href='https://www.kaggle.com/blastchar/telco-customer-churn'>Kaggle</a></figcaption>
</figure>

- Exploring and predicting customer churn can help develop customer retention programs to keep them from leaving
- For this exercise, let's pretend we want to be able to predict which customers will churn so we can give them a discount to keep them as customers         
- Let's load the dataset and explore it:

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
#code to see all columns
pd.set_option('display.max_columns', None)

data = pd.read_csv('datasets/WA_Fn-UseC_-Telco-Customer-Churn.csv', encoding='utf-8') #encoding ensures the format is correct for the data
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
print('The dataset has %.0f rows and %.0f columns.' % (data.shape[0], data.shape[1]))

The dataset has 7043 rows and 21 columns.

- If you scroll to the right of the DataFrame, you'll find our target variable labeled "churn." Values are "Yes" and "No"
- Next, Let's check the type for each column
- This can be an initial step for determing next steps for data cleaning

In [4]:
data.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

- As suspected, most of the features are either `objects` or `strings`
- Next, let's see if there are any missing values in our dataset

In [5]:
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

<a id="ex1"></a>

### Exercise 1 (EDA)

Find the counts of the values of each categorical column

In [20]:
# YOUR CODE HERE: 
for col in data.select_dtypes(include=['object']).columns:
    print (f'The columns is {col}')
    print (f'The count of values is {data[col].value_counts()}' ,"\n"*2,"-"*129,"\n")

The columns is customerID
The count of values is 7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
             ..
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
4304-TSPVK    1
3186-AJIEK    1
Name: customerID, Length: 7043, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is gender
The count of values is Male      3555
Female    3488
Name: gender, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is Partner
The count of values is No     3641
Yes    3402
Name: Partner, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is Dependents
The count of values is No     4933
Yes    2110
Name: Dependents, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is PhoneService
The count of values is Yes    6361
No      682
Name: PhoneService, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is MultipleLines
The count of values is No                  3390
Yes                 2971
No phone service     682
Name: MultipleLines, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is InternetService
The count of values is Fiber optic    3096
DSL            2421
No             1526
Name: InternetService, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is OnlineSecurity
The count of values is No                     3498
Yes                    2019
No internet service    1526
Name: OnlineSecurity, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is OnlineBackup
The count of values is No                     3088
Yes                    2429
No internet service    1526
Name: OnlineBackup, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is DeviceProtection
The count of values is No                     3095
Yes                    2422
No internet service    1526
Name: DeviceProtection, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is TechSupport
The count of values is No                     3473
Yes                    2044
No internet service    1526
Name: TechSupport, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is StreamingTV
The count of values is No                     2810
Yes                    2707
No internet service    1526
Name: StreamingTV, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is StreamingMovies
The count of values is No                     2785
Yes                    2732
No internet service    1526
Name: StreamingMovies, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is Contract
The count of values is Month-to-month    3875
Two year          1695
One year          1473
Name: Contract, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is PaperlessBilling
The count of values is Yes    4171
No     2872
Name: PaperlessBilling, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is PaymentMethod
The count of values is Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: PaymentMethod, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is TotalCharges
The count of values is           11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: TotalCharges, Length: 6531, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

The columns is Churn
The count of values is No     5174
Yes    1869
Name: Churn, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

- Interestingly, there seems to be different descriptions (values) per feature.
    - It's not just "Yes" or "No"
    - For example, in the `MultipleLines` column instead of `Yes/No` there's another description `No phone service`.    
- Now that we've explored the dataset, we got some cleaning to do

<a id="ex2"></a>

- There's a few changes we can make.
- To simplify and have binary features, if `No internet service` or `No phone service` is present, we'll change this to `No`.
     - How should we accomplish this task?
- If you recall, Machine Learning algorithms can only accept numbers as inputs
    - Many of our features, even if they're binary "Yes/No" cannot be used in their present state
    - This is evidenced if you run the `.dtypes` method
        - Features with strings cannot be used as inputs        
- How can we fix this?

##### Label Encoder

- One way we can do this is with Sklearn's [LabelEncoder()](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)
- Encode labels with value between 0 and n_classes-1
- It labels automatically so we cannot determine the encoded values

<details>

<summary>Click Me: Label Encoder</summary>

<figure>
  <img src='img/lab_encod.png'/>
  <figcaption>Image from <a href='https://web-buzz.in/labelencoder-and-onehotencoder/'>WebBuzz</a></figcaption>
</figure>
</details>

- Let's take a look at the `Contract` feature

In [21]:
data.Contract.value_counts()

Month-to-month    3875
Two year          1695
One year          1473
Name: Contract, dtype: int64

- There are three classes in this feature.
- Let's run it through the LabelEncoder algorithm

In [22]:
from sklearn.preprocessing import LabelEncoder

data['Contract'] = LabelEncoder().fit_transform(data.Contract.values)
data.Contract.value_counts()

0    3875
2    1695
1    1473
Name: Contract, dtype: int64

- As you can see, the feature has now been encoded into numbers
- `dtype` is also `int64`
- Let's take a look at our dataset again and see what else needs to be changed

In [ ]:
#peek at our data
data.head()

<a id="third"></a>
##### Third Class
- Remember when we checked the `value_counts` of the categorical columns?
    - Some of these features had `Yes`, `No`, and another class such as `No internet service`
    - You can see these columns below:

In [13]:
# columns with the third class
columns_to_change = ['MultipleLines', 'OnlineSecurity', 'OnlineBackup',
                     'DeviceProtection', 'TechSupport', 'StreamingTV', 
                     'StreamingMovies'
                    ]
for column in columns_to_change:
    print(data[column].value_counts(), '\n' * 2, '-' * 129, '\n')

No                  3390
Yes                 2971
No phone service     682
Name: MultipleLines, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

No                     3498
Yes                    2019
No internet service    1526
Name: OnlineSecurity, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

No                     3088
Yes                    2429
No internet service    1526
Name: OnlineBackup, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

No                     3095
Yes                    2422
No internet service    1526
Name: DeviceProtection, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

No                     3473
Yes                    2044
No internet service    1526
Name: TechSupport, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

No                     2810
Yes                    2707
No internet service    1526
Name: StreamingTV, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

No                     2785
Yes                    2732
No internet service    1526
Name: StreamingMovies, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

- For these, we will manually change this third class to `No`

In [ ]:
#change third class to 'No'
for column in columns_to_change:
  data[column] = data[column].apply(lambda x: 'No' if ((x == 'No internet service') 
                                                       or (x == 'No phone service') 
                                                       or (x == 'No')) 
                                                else 'Yes')
  print(data[column].value_counts(), '\n' * 2, '-' * 129, '\n')

- These next features have binary classes, but they're not `Yes` or `No`
- Similar to above, we'll manually encode them to `0` and `1`

In [ ]:
print('Classes before encoding:', '\n' * 2, data['PaymentMethod'].value_counts(), '\n' * 2, '-' * 129, '\n')
data['PaymentMethod'] = data['PaymentMethod'].apply(lambda x: 0 if ((x == 'Electronic check') 
                                                                   or (x == 'Mailed check')) 
                                                                else 1)
print('Classes after encoding:', '\n' * 2, data['PaymentMethod'].value_counts())

Lastly, we'll convert all binary cases to 0 and 1.

In [26]:
# YOUR TURN: Repeat the same exercise for the Gender column
data['gender'] = LabelEncoder().fit_transform(data.gender.values)

In [28]:
# YOUR TURN: Repeat the same exercise for the InternetService column

data['InternetService'] = data['InternetService'].apply(lambda x: 0 if x=='No' else 1)

In [30]:
# Let's see what the dataset looks like now
data.shape

(7043, 21)

In [33]:
# Let's see what the dataset looks like now
data.customerID.nunique()

7043

- We're going to manually encode the binary features to either `0` or `1`
- Note we're not including (`.drop`) certain columns:
    - `customerID` is not a feature but a string that denotes a unique customer
    - The other four features are continuous

In [34]:
columns = data.columns.drop(['customerID', 
                             'tenure', 
                             'Contract',
                             'MonthlyCharges', 
                             'TotalCharges'])


## labelling the binary data into 0 and 1 from False and True
for column in columns:
    data[column] = data[column].apply(lambda x: 0 if x == 'No' or x == 0 else 1)
    print(data[column].value_counts(), '\n' * 2, '-' * 129, '\n')

1    3555
0    3488
Name: gender, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

0    5901
1    1142
Name: SeniorCitizen, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

0    3641
1    3402
Name: Partner, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

0    4933
1    2110
Name: Dependents, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    6361
0     682
Name: PhoneService, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    3653
0    3390
Name: MultipleLines, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    5517
0    1526
Name: InternetService, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    3545
0    3498
Name: OnlineSecurity, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    3955
0    3088
Name: OnlineBackup, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    3948
0    3095
Name: DeviceProtection, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    3570
0    3473
Name: TechSupport, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    4233
0    2810
Name: StreamingTV, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    4258
0    2785
Name: StreamingMovies, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    4171
0    2872
Name: PaperlessBilling, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

1    7043
Name: PaymentMethod, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

0    5174
1    1869
Name: Churn, dtype: int64

 ---------------------------------------------------------------------------------------------------------------------------------

<a id="numstring"></a>
##### Numeric Column as String

- Look at the `.dtypes` method below.
    - What do you notice?
    - Do you see any issues?
    - If it helps, look at the `.head()` of our dataframe
    
<details>

<summary>Click Me: Answer</summary>

The `TotalCharges` column is a string, but it looks like a numeric and continuous feature.
    
</details>

- What's going on?

In [35]:
data.dtypes

customerID           object
gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService       int64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract              int64
PaperlessBilling      int64
PaymentMethod         int64
MonthlyCharges      float64
TotalCharges         object
Churn                 int64
dtype: object

In [36]:
#Peek at our data
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,1,1,0,1,0,0,0,0,0,1,1,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,0,1,1,0,1,0,0,0,1,0,1,56.95,1889.5,0
2,3668-QPYBK,1,0,0,0,2,1,0,1,1,1,0,0,0,0,0,1,1,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,45,0,1,1,1,0,1,1,0,0,1,0,1,42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,1,70.70,151.65,1

- Does this mean there are still missing values in our dataset?

In [37]:
data['TotalCharges'].isnull().sum()

0

- How can their be no missing values but our column is still a string?
- Let's discuss!

In [40]:
data.TotalCharges.values[:5]

array(['29.85', '1889.5', '108.15', '1840.75', '151.65'], dtype=object)

In [42]:
#Looking for spaces in the column. Note the .str method is needed for Pandas Series
data[data['TotalCharges'].str.isspace()].TotalCha

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,0,0,1,1,0,0,1,1,1,0,1,1,1,0,2,1,1,52.55,,0
753,3115-CZMZD,1,0,0,1,0,1,0,0,1,1,1,1,1,1,2,0,1,20.25,,0
936,5709-LVOEQ,0,0,1,1,0,1,0,1,1,1,1,0,1,1,2,0,1,80.85,,0
1082,4367-NUYAO,1,0,1,1,0,1,1,0,1,1,1,1,1,1,2,0,1,25.75,,0
1340,1371-DWPAZ,0,0,1,1,0,0,1,1,1,1,1,1,1,0,2,0,1,56.05,,0
3331,7644-OMVMY,1,0,1,1,0,1,0,0,1,1,1,1,1,1,2,0,1,19.85,,0
3826,3213-VVOLG,1,0,1,1,0,1,1,0,1,1,1,1,1,1,2,0,1,25.35,,0
4380,2520-SGTTA,0,0,1,1,0,1,0,0,1,1,1,1,1,1,2,0,1,20.00,,0
5218,2923-ARZLG,1,0,1,1,0,1,0,0,1,1,1,1,1,1,1,1,1,19.70,,0
6670,4075-WKNIU,0,0,1,1,0,1,1,1,0,1,1,1,1,0,2,0,1,73.35,,0
6754,2775-SEFEE,1,0,0,1,0,1,1,1,1,1,0,1,0,0,2,1,1,61.90,,0

In [ ]:
# Having NaN values, spaces, symbols like $ etc in your data can force them to be objects
# Subsetting the dataFrame to find rows with spaces in them
data[data['TotalCharges'].str.isspace() == True]

- Depending on how missing values were recorded  missing values we missed initially!
- Thankfully, it's 11 rows and it shouldn't affect our prediction.    
- We'll just drop those rows

In [43]:
# First, turn those empty spaces into nans
data['TotalCharges'].replace(' ', np.nan, inplace=True)

# Confirmation those 11 rows are nans
data.TotalCharges.isna().sum()

11

In [44]:
# Now we'll drop empty rows
data.dropna(subset=['TotalCharges'], inplace=True)

# We'll change the feature type to numeric
data['TotalCharges'] = data.TotalCharges.astype('float64')

print('Our dataset now has %.0f rows and %.0f columns.' % (data.shape[0], data.shape[1]))

Our dataset now has 7032 rows and 21 columns.

In [45]:
# Confirming the columns are numeric
data.dtypes

customerID           object
gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService       int64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract              int64
PaperlessBilling      int64
PaymentMethod         int64
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

In [46]:
# Peek at our dataset
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,1,1,0,1,0,0,0,0,0,1,1,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,0,1,1,0,1,0,0,0,1,0,1,56.95,1889.50,0
2,3668-QPYBK,1,0,0,0,2,1,0,1,1,1,0,0,0,0,0,1,1,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,45,0,1,1,1,0,1,1,0,0,1,0,1,42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,1,70.70,151.65,1

<a id="feat_sel"></a>
### Feature Selection

- There are multiple ways to perform Feature Selection
- When preparing data for logistic regression (or most classification models), it is recommended to determine any causal relationships between features. 
    - This will help generalize the model to new and unseen data.
- Just like in our lesson with Linear Regression, we will use a **Correlation Plot** to select our features

In [ ]:
# copy data to new df
data_cp = data.copy()

# drop customerID as it's not a feature
data_cp = data_cp.drop(['customerID'], axis=1)

data_cp.head()

- Let's take a quick look at two features related to "Charges"
- We'll use the `.corr()` method to calculate the correlation between the two features
    - Remember that correlation between two variables ranges from (+/-) 1 to 0, with highest correlation at (+/-) 1

In [ ]:
data['MonthlyCharges'].corr(data['TotalCharges'])

- As expected, it looks like the columns for charges have a high positive correlation.
- We'll explore all the correlations between pairwise variables using Seaborn's Heatmap method:

In [ ]:
import seaborn as sns

sns.set(style="white")

# Compute the correlation matrix
corr = data_cp.corr()

# Generate a mask for the upper triangle
mask = np.zeros_like(corr, dtype=bool)
mask[np.triu_indices_from(mask)] = True

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(220, 10, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr,annote=True,mask=mask, cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})

- We can also see the correlation values in a DataFrame

In [ ]:
df = pd.DataFrame()
df = data_cp.corr() # .corr returns as a DataFrame value
df

- That's a lot to look at so we can subset any column
- We usually look at correlations between independent features and the target variable:

In [ ]:
# Output just the correlation values versus the Target variable (Churn)
# Therefore you would be able to look at specific columns 
df['Churn']

- Let's take some of the features above that have some higher correlation with `Churn` and display it with a pairplot
- Seaborn's `.pairplot()` method allows us to beautifully display pairwise relationships between variables
- The diagonal is each feature's relationship to itself.
    - It can be displayed as histograms, kde density plots, and more
- The upper and lower halves of the triangle represent scatter plots between two variables
    - Notice the `hue='Churn'` argument below:
    - It colors the data points based on whether a customer churned (orange) or didn't churn (blue)
    - This helps give more context to the plots

In [ ]:
# Display pairplot
plt.figure()
sns.pairplot(data=data[["tenure",
                        "TechSupport",
                        "Contract",
                        "PaymentMethod",
                        "MonthlyCharges",
                        "TotalCharges",
                        "Churn"
                      ]], hue='Churn')

- **QUESTION**: What do you notice in both the **Heatmap** and **Pairplot**? What features would you keep and or drop? Why?

<details>
<summary>Click Me: Possible Solution</summary>

- Since `MonthlyCharges` and `TotalCharges` are proven to have a strong correlation with each other, we'll drop one of these. 
- `customerID` was already dropped since it has all unique strings and provides no value to the prediction.     
- `tenure` also seems to correlate with `Contract` and both "Charges" columns. 
    - One solution is to bin the continuous values of this feature, but for this lesson, we'll just drop it. 
- Feel free to do your own analysis and cite appropriate reasons to drop relevant features    
</details>

In [ ]:
data_cp = data_cp.drop(['tenure', 'MonthlyCharges'], axis=1)
data_cp.head()

<a id="ex3"></a>

### Training the Model

- We follow similar steps to what we did for Logistic Regression

In [ ]:
# Peek at our dataset
data_cp.head()

In [ ]:
# Subset our target feature
y = data_cp['Churn']

# All the other features are independent variables
X = data_cp.drop(['Churn'], axis=1)

In [ ]:
# Split the dataset into train and test
from sklearn.model_selection import train_test_split

# Split our dataset into training and test sets
x_train, x_test, y_train, y_test = \
  train_test_split(X, y, test_size=0.25, random_state=123)

In [ ]:
# Import the model → present in 
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

# Why do you think the model resides in the linear_model subpackage?

In [ ]:
# Fit the model
logreg.fit(x_train, y_train)

<a id="hyp_param"></a>

### Hyperparameters: A Gentle Introduction

- Before we predict on our test set, let's talk about hyperparameters
- User-defined "settings" for a model that need to be configured to improve performace
    - Each algorithm (inc Linear Regression) have their own hyperparameters, ranging from simple to complex
    - Hyperparameters → Learning How to Learn, Parameters (like model coefficients etc) → What You Learn
- Picking good hyperparameters → Hyperparameter _tuning_ or _optimization_
  - Like tuning a guitar!
- Another analogy for ML Hyperparameter tuning is a control panel with knobs and dials:

<details>

<summary>Click Me: Knobs and Dials!</summary>

<figure>
  <img src='img/knobs.png' width='50%'/>
  <figcaption>Image from <a href='https://dribbble.com/shots/4781636-Dial-Knob-2'>Dribbble.com</a></figcaption>
</figure>

</details>

- For Logistic Regression, we just trained the model with its **default settings**
- As you can see, the `.get_params()` method shows a **dictionary** of the following hyperparameters:

In [ ]:
# Look at the hyperparameters
logreg.get_params()

- In the dictionary, each `key` is the hyperparameter name with the corresponding `value` is the setting. The `.get_params()` method specifies exactly how the model was trained
    - How to do that is beyond the scope of this lesson, but just know there are many "dials and knobs" to adjust.
    - We'll go over some of these hyperparameters in a future lesson, but just know they exist and can be tuned.

In [ ]:
# predict on test set
pred = logreg.predict(x_test)

In [ ]:
from sklearn import metrics

# Compare the accuracy between the actual values and predictions
accuracy_score = metrics.accuracy_score(y_test, pred)
print(f'Accuracy Score: {accuracy_score}')

- Sklearn's `accuracy_score` method uses the proportion of **correct** predicitons over **all** the predicted values
- Ranges from 0 to 1 with 1 being the best as it represents 100% accuracy
- However, what does accuracy mean for a classification model?
- Remember, that we have two classes we're looking at (Churn and No Churn)
    - Does the 77% weigh equally for both of them?
- What if it's really high for one class and much lower for the other?
    - Is there a way to see all this information and evaluate them?

<a id="eval"></a>
## Evaluation Metrics
- We'll now introduce some common ways of evaluating classification models

<a id="matrix"></a>

### Confusion Matrix

- We wanted to know more about what this looks like, especially in regards to churn
- Remember, customer who churn (class 1) is who we're most interested in
- It all starts with the Confusion Matrix

<details>

<summary>Click Me: Confusion Matrix!</summary>

<figure>
  <img src='img/confusion_matrix.png'/>
  <figcaption>Image from <a href='https://towardsdatascience.com/understanding-confusion-matrix-a9ad42dcfd62'>TowardsDataScience.com</a></figcaption>
</figure>

</details>

- In a nutshell, it shows our model's prediction vs the actual value for each class
- This is what it looks like for our data:

In [ ]:
#importing sklearn confusion matrix
from sklearn.metrics import confusion_matrix
    
# Creating a confusion matrix
con_mat = confusion_matrix(y_test, pred)
con_mat = pd.DataFrame(con_mat, range(2), range(2))
   
#Ploting the confusion matrix
plt.figure(figsize=(6,6))
plt.title("0 = No Churn          1 = Churn") # The spacing is intentional
sns.set(font_scale=1.5) 
sns.heatmap(con_mat, annot=True, annot_kws={"size": 16}, fmt='g', cmap='Blues', cbar=False)
plt.ylabel("Actual Values")
plt.xlabel("Predicted Values")
plt.show()

In [ ]:
# YOUR TURN: sklear also has a function ConfusionMatrixDisplay to plot and visualize the confusion matrix
# Check it out!

1. The **diagonal** represents the number of correct classifications for each class: 
    - Look at the top left square:
        - Class 0: 1130/1234 were correctly predicted
        - 1130 represents the term **True Negatives (TN)**
        - Of all the 1234 total customers who **did not** churn, our model correctly predicted 1130 of them.
        - This represents the number of predictions that were correctly predicted to be class 0 (no churn)
    - Look at the bottom right square:
        - This is our class of interest
        - Class 1: 224/524 were correctly predicted
        - 224 represents the term **True Positives (TP)**
        - Of all the 524 total customers who **did** churn, our model correctly predicted 224 of them. 
        - This represents the number of predictions that were correctly predicted to be class 1 (churn)
2. Therefore the other elements, of the matrix, are the misclassified values: 
    - Look at the top right square:
        - Class 0: 104/1234 were incorrectly predicted
        - 104 represents the term **False Positives (FP)**
        - Of all the 1234 total customers who **did not** churn, our model misclassified 104 of them. 
        - This represents the number of predictions that were incorrectly predicted to be class 0 (churn)
    - Look at the bottom left square:
        - Class 1: 300/524 were incorrectly predicted
        - 300 represents the term **False Negatives (FN)**
        - Of all the 524 total customers who **did** churn, our model misclassified 300 of them.
        - This represents the number of predictions that were incorrectly predicted to be class 0 (no churn)
- Another way to visualize the Confusion Matrix is via the Pandas `.crosstab()` method
- Note: Crosstab allows us to see the **supports** of the matrix which are just the totals
    - Represented by the `All` row and column 
    - Example: Total (1430) of all the customers (1130 + 300) the model **predicted** to **not** churn.

In [ ]:
# Pandas crosstab method creates a confusion matrix for us
df_matrix = pd.crosstab(y_test, pred, rownames=['True'], colnames=['Predicted'], margins=True)
df_matrix

- The Confusion Matrix is the basis for all the other classification evaluation metrics
  - It's with this raw data (TP, TN, FP, FN) that the other metrics are calculated
  - Remember our `77%` accuracy score?
      - That too was calculated from this matrix
- Take a look at the picture below for a quick but overwhelming snapshot of a confusion matrix "cheat sheet"
  - Note: The picture has the "predicted" and "actual" conditions (values) swapped.

<details>

<summary>Click Me: Oh My Matrix!</summary>

<figure>
  <img src='img/confusion_matrix_full.png'/>
  <figcaption>Image from <a href='https://kyleake.medium.com/classification-evaluation-scheme-the-breakdown-of-confusion-matrix-7b8066e978aa'>Kyleake.medium.com</a></figcaption>
</figure>

</details>

- Thankfully, we won't talk about all those concepts in this lesson
- Just know that it's all derived from the numbers in the 4 squares of the matrix

<a id="imbalance"></a>
### Data imbalance

- Let's go back to our `77%` accuracy score that our model originally received
- Compare it to our Confusion Matrix
- What do you notice? Is there anything incongruent between our score and the confusion matrix?

<figure>
  <img src='img/confusion_matrix_churn.png' width='40%'/>
</figure>

<details>

<summary>Click Me: Answer!</summary>

- Remember, we want to our model to accurately predict customers who will churn
- As you can see, over half of our churned customers (300/524) were incorrectly misclassified
- That means our model has an "accuracy" of about `43%` when predicting (classifying) churned customers
- Not aligned with the 77% which was our original score

</details>

- One common issue that Data Scientists have to deal with is **Class Imbalance**
- What does this mean?
- Let's take a look at our target variable `Churn`:

In [ ]:
data.Churn.value_counts()

- There are more than double the amount of customers who churned vs customers who didn't churn

In [ ]:
churn_no = data.Churn.value_counts()[0] # 5174
churn_yes = data.Churn.value_counts()[1] # 1869

no = churn_no / (churn_no + churn_yes) # 5174 / (5174 + 1869)
yes = 1 - no # (1 - 0.73)

class_weight={0:no, 1:yes}
print(class_weight)

- With approximately `74%` of data being "no churn", we could say the data is **biased** or **skewed** towards the "no churn" class
- This is a common classification issue known as **Data Imbalance**
    - Examples include fraud detection, spam detection, customer conversions, and cancer detection
        
<details>

<summary>Click Me: Imbalanced Target Variable Visualized</summary>

<figure>
  <img src='img/class_heat_stroke.png'/>
  <figcaption>Image from <a href='https://www.analyticsvidhya.com/blog/2020/10/improve-class-imbalance-class-weights/'>AnalyticsVidhya</a></figcaption>
</figure>
</details>        

- **Majority Class** has most of the values
    - In our dataset, it is "No Churn"
- **Minority Class** is the opposite with much less samples
    - In our dataset, it is "Yes Churn"  
- Most of the times, our we're interested in the Minority Class
    - In our dataset, we want to predict which customers will churn
- This presents a problem as ML algorithms assume **equal** distribution of classes
    - Naive application of a model might train mostly on the characteristics of the majority class and neglect the important characteristics of the minority class
- The subject of **Class Imbalance** is a huge topic and there are numerous strategies to tackle this problem
    - For this reason, we cannot naively score our models based purely on **accuracy**
    - We will cover this later in a notebook
 - What then should be measured?
- If accuracy is not a good metric, how else can we determine if our model is good?

<a id="class_rep"></a>
### Classification Report

- A Classification report is used to measure the quality of predictions from a classification algorithm. 
- More specifically, True Positives (TP), False Positives (FP), True Negatives (TN) and False Negatives (FP) are used to predict the metrics of a classification report (Remember the Confusion Matrix)
- The report shows the main classification metrics **precision, recall and f1-score** for each class.
- Everything in the report has a number between 0 and 1 with 1 being the best (or 100%)
- sklearn has a `classification_report()` method that automatically computes these metrics for us
- Let's take a look below:

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred, target_names= ['Not Churned (0)', 'Churned (1)']))

<a id="prec"></a>
#### Precision and Recall

- Precision and Recall are very confusing topics, especially because they sound similar to each other
    - We'll spend a little longer here to introduce these topics
- Formula: The following are the Formulas for Precision and Recall
    - `Precision = TP / (TP + FP)` 
    - `Recall = TP / (TP + FN)`
- Let's explore it with a visual example:

<details>

<summary>Click Me: Recall and Precision Visualized</summary>

<figure>
  <img src='img/prec_rec_vis.png'/>
  <figcaption>Image from <a href='https://towardsdatascience.com/whats-the-deal-with-accuracy-precision-recall-and-f1-f5d8b4db1021'>TowardsDataScience.com</a></figcaption>
</figure>
</details>

** There are other analogies as well:**

1. Suppose you are asked to name everyone in this room besides yourself (assume 10 other people in the room). 
    - You are given **20 tries** to correctly identify everyone:
    - You are able to **recall** all 10 people. 
        - Your ratio is 10/10 or 100%. 
    - You are able to **recall** only 6 people out of the 10 correct answers. 
        - Your ratio is 6/10 or 60%.
    - You were able to recall all 10 people but you needed all 20 guesses. 
        - Your **precision** ratio is 10/20 or 50%
2. This next example comes from [here](https://datascience.stackexchange.com/questions/64441/how-to-interpret-classification-report-of-scikit-learn):
    - Let's picture Precision and Recall as **netting a drove of fishes**.        
    - Imagine, we're boating over the sea and lay down our net.            
    - If the **drove of fishes is huge**, while **the net is pretty small**:
        - The net will be full of fish, meaning **Precision is high**.
        - But we only get a minority of the drove, meaning **Recall is low**.            
    - If there is just a **tiny drove of fishes**, but we got **a huge net**: 
        - We will see that just a small fraction of the net have fishes, meaning **Precision is low**. 
        - But fortunately, we catch every fish in the drove, meaning **Recall is high**.

**Now let's try to *recall* the concepts using word associations:**

<details>

<summary>Click Me: Recall and Precision Word Games</summary>

<figure>
  <img src='img/prec_rec_words.png' width='50%'/>
  <figcaption>Image from <a href='https://towardsdatascience.com/precision-and-recall-made-simple-afb5e098970f'>TowardsDataScience.com</a></figcaption>
</figure>
</details>

**Let's try this with our data:**

<details>

<summary>Click Me: Answer!</summary>
    
- Precision:
    - Of all the customers **predicted** as churned, how many **really** churned? (Class 1)
    - Of all the customers **predicted** as *not* churned, how many **really** did *not* churn? (Class 0)

- Recall:
    - Of all the customers who **really** did churn, how many are **predicted** as churned? (Class 1)
    - Of all the customers who **really** did *not* churn, how many are **predicted** as *not* churned? (Class 0)

</details>

- Last, let's calculate Precision and Recall for the positive class (customers who churned or class 1)
    - Below is the Visualized Confusion Matrix
    - Here are the formulas again:
        - `Precision = TP / (TP + FP)`
        - `Recall = TP / (TP + FN)`<br><br>  

<figure>
  <img src='img/confusion_matrix_churn.png' width='40%'/>
</figure>

<br>

<details>

<summary>Click Me: Answer!</summary>
    
- Precision and Recall for Class 1 (Churned):
    - `Precision = TP / (TP + FP)` or `224 / (224 + 104) = 0.691`
    - `Recall = TP / (TP + FN)` or `224 / (224 + 300) = 0.427`

</details>

- As we can see below, the Precision and Recall values we calculated are about the same as sklearn's Classification Report

In [ ]:
print(classification_report(y_test, pred, target_names= ['Not Churned (0)', 'Churned (1)']))

<a id="f1"></a>
#### F1 Score

- How do we score our model given that we have both metrics Precision and Recall?
- This is where the F1 score comes in → "harmonic mean" between precision and recall
    - A form of weighted average of both
    - It's a good metric to use when both precision and recall are important
-  What’s the difference between this metric and accuracy?
    - False positives (FP) and false negatives (FN) can really hurt a model, while true negatives (TN) are often less important to what we're trying to solve especially in a business setting.
    - The F1 score tries to take this into account, giving more weight to false negatives (FN) and false positives (FP) while not letting large numbers of true negatives (TN) influence your score.
        - We can see that our f1-score of 0.53 paints a different portrait than our original accuracy score of 0.77 would lead us to believe
    - For our **imbalanced** dataset, we would care more about the F1 score for our **Churned (1)** class than Not Churned **(0)**.   
- F1 Score is a good starting metric for evaluating binary and imbalanced classification

<a id="acc"></a>
#### Accuracy, Macro Avg, Weighted Avg

- **Accuracy** is simply the amount of correct predictions over our total.
    - It's easy to miss in the Classification Report, and it's the third number under the "f1-score" column
    - It's a more useful metric when both classes are more balanced and are equally important in the study
- **macro avg** is simply the unweighted average of both classes for each metric in its column
    - For example, In the "precision" column, 0.79 + 0.68 = 0.74
    - It does the same for recall and f1-score
- **weighted avg** does some fancy math to add weights to the class' average
    - Essentially, it adds a weight depending on the number of **True** labels for the class
    - Therefore, it tends to favor the majority class
        - Not as useful for imbalanced classification where we care more about the minority class
- Note: **macro avg and weighted avg** are good for seeing an overall picture of the scores
    - Used more for **multi-class** classification (ours is just binary)

In [ ]:
print(metrics.classification_report(y_test, pred), '\n' * 2, '-' * 129, '\n')
df_matrix

<a id="rocauc"></a>
### ROC-AUC

- Chances are we will never get perfect accuracy between both precision and recall
- In fact, there is often a "tug of war" between both metrics

<figure>
  <img src='img/pr_tug.png'/>
  <figcaption>Image from <a href='https://medium.com/geekculture/accuracy-precision-and-recall-in-plain-english-1c90c92a6c88'>Medium</a></figcaption>
</figure>

- In binary classification, we often make trade-offs between higher precision or higher recall
- Optimizing for one hurts the other which leads to more errors:
  - False Positivies or False Negatives
- In our dataset, we're trying to figure out which customers will churn (class 1) out of all the customers. For the customers who we predict to churn, we will offer them a discount to hopefully prevent them from leaving
- Our model correctly predicts 224 churned customers out of 524 total. 
    - This is 224/524 which equals 0.43 which is our Recall.
    - 43% is pretty low
- It costs the company more money to get new customers than to keep the ones we have. However, if we want our model to catch more churned customers then the trade-off will be incorrectly classifing customers we predicted to churn but in fact did not leave
    - In the Confusion Matrix, these are known as False Positives (FP)
    - We could tune the model to get 100% of the churned customers, but then we would have too many FPs
    - In the business context, it would be the equivalent of offering discounts to everyone which would be a waste of money for those who were never planning on leaving            
- Isn't there a way we could see the differing Recall percentages against the amount of False Positives? In fact there is!

- **ROC Curve - AUC Score** (Receiver Operating Characteristics curve (ROC) and Area under the Curve (AUC) Score) are 2 very popular metrics among data scientists.
- Let’s start understanding this with an example:
- We have a classification model that gives probability values ranging between 0–1 to predict the probability of a customer churning or not.
- A probability score near 0 indicates a very low probability that the customer will churn whereas a probability near 1 indicates a very high probability of a customer churning.
- Now, by default if we consider a threshold of 0.5 then all the customers assigned probabilities ≤0.5 will be classified as “No Churn” and people assigned probabilities >0.5 will be classified as “Churn”.
    - This is what we did when we predicted using our Logistic Regression model
    - Each person was assigned a probability, and based on that number, was labeled as either "churn" or "no churn"
    - Sklearn did it automatically so we never actually saw the probabilities for each customer
- The ROC curve shows us how the model predicted the classes (churn or not churn) if the threshold was different
    - Instead of the default threshold 0.50, the ROC shows what happens if we vary it     
    - For example, What if we make it 0.3 or 0.9?

<a id="roc"></a>

#### Plot the ROC

- A few characteristics of the AUC for a ROC curve:
    - Only concerned about the score for the positive (1) class
    - It is a popular diagnostic tool for classifiers on balanced and imbalanced binary prediction problems alike because it is not biased to the majority or minority class.
- ROC-AUC consists of:
    - **False Positive Rate (FPR, fall-out)** on the x-axis
        - This is the number of falsely predicted values in 1 class (0s predicted as 1s) with respect to all 0 data points
    - Mathematically, $\frac{FP}{FP + TN}$    
    - **True Positive Rate (TPR, recall)** on its y-axis
        - This is the number of correctly predicted values in 1 class (1s predicted as 1s) with respect to all 1 data points
        - Mathematically, $\frac{TP}{TP + FN}$
- It might make more sense once we implement it via sklearn
    - Note, we implement the ROC-AUC after the step where we train our Logistic Regression model
        - Usually, we would predict `x_test` to get the class label. Instead, we use the `predict_proba()` method to get the probabilities.
- Take a look at it below

In [ ]:
pred_proba = logreg.predict_proba(x_test)
df_pred_proba = pd.DataFrame(pred_proba * 100, columns=['% Not Churn', '% Churn'])
df_pred_proba.head()

- Above, each row is a customer with the model's predicted probability they will either churn or not churn
- We turned the array into a DataFrame to help with understanding, but here is what the actual array looks like:

In [ ]:
# array of probability predictions
pred_proba

- The resulting output is an array of lists where each list consist of 2 numbers. 
    - All probabilities on the left side is the probability of a data point being classified as 0 (no churn).
    - The right is the probability for 1 (churn).
- We can now take this list of probabilities and use it to calculate the ROC curve 
    - Again we are only focusing on class 1 (or the right side) which is all values with index

In [ ]:
from sklearn.metrics import roc_curve, auc

# Note that the third return value is not needed but still needs a placeholder "_"
# fpr = False Positive Rate, tpr = True Positive Rate 
fpr, tpr, _ = roc_curve(y_test, pred_proba[:, 1]) #pred_proba[:,1] just means the 2nd column (class 1)

fpr[100], tpr[100]

- You can see that the resulting output for fpr and tpr is an array.
- If we choose a random index 100, we get two values.
    - This corresponds to a coordinate on the ROC curve.

In [ ]:
# Compute AUC score
roc_auc = auc(fpr, tpr)

# Plot ROC curve with AUC score
import matplotlib.pyplot as plt

plt.figure()
lw = 2
plt.plot(fpr, tpr, color='b', lw=lw, 
         label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='r', lw=lw, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic (ROC)')
plt.legend(loc="lower right")
plt.show()

**Let's look at the graph:**

- The `fpr` (False Positive Rate) was plotted along the x-axis
- The `tpr` (True Positive Rate) was plotted along the y-axis
- Each of the points of the (fpr, tpr) pair are plotted on the plain which leads to the blue line
- We can think of the plot as the fraction of correct predictions for the positive class (y-axis) versus the fraction of errors for the negative class (x-axis).
- The **red line** is a benchmark used to gauge the curve
    - It indicates the points where tpr = fpr
    - It's the equivalent of a random classifier or a 50-50 coin toss, and any point of the curve above red line means the model is better than random chance
- Pay attention to how the **blue line** curves.
    - On the top right, tpr = 1 and fpr = 1
        - This means at this threshold, the model would correctly classify 100% of the customers who churned but also incorrectly predict customers as churning, when they in fact did not, 100% of the time
    - On the bottom left is the other extreme which is tpr = 0 and fpr = 0
        - At this point, our model incorrectly classifies churning customers as non-churning 100% of the time, and correctly classifies non-churning customers as non-churning 100% of the time
            - Note: equation for fpr: 
                - FPR = 1 - TNR (or True Negative Rate)
                - Substitute fpr = 0 in the equation: 0 = 1 - TNR
                - TNR = 1 (or 100%)
    - Either extreme is not helpful to us
- Why is the curve useful?
    - The curve is useful because we have visual of the tradeoffs between `fpr` and `tpr`
    - For example, let's say your boss wants our model to be able to correctly predict churning customers at least 80% of the time, on average. 
        - If you go to `0.8` on the y-axis, you'll see that it corresponds to about `0.25` on the x-axis
        - This means that in order for our model to correctly predict churning customers an average of at least 80% of the time, we'll have to be willing to accept that it also misclassifies non-churning customers as churning about 25% of the time

<a id="auc"></a>

#### AUC

- Another reason why the ROC curve is useful is that we can get the Area Under the Curve (AUC) which is a useful metric for scoring and comparing models
    - Ranges from 0 (very poor) to 1 (very good)
- There are two ways to compute the AUC score through Sklearn:
    1. `roc_curve()` -> `auc()`: Used for plotting the AUC
    2. `roc_auc_score()`: When only trying to see the score
- First, compute the AUC score with `auc()`
    - We actually already did this when we plotted our ROC curve
    - We'll put the code below again

In [ ]:
#import roc_curve and the auc functions
from sklearn.metrics import roc_curve, auc

# compute the fpr and tpr 
fpr, tpr, _ = roc_curve(y_test, pred_proba[:, 1])

# Compute AUC score
roc_auc = auc(fpr, tpr)
print("ROC-AUC Score:", roc_auc)

- Note: The ROC-AUC score can only be predicted using the **probabilities** of the prediction. For classifiers in sklearn, use `predict_proba()` instead of `predict`.
- The other way we can calculate the ROC-AUC score is directly via the `roc_auc_score()` as seen below:

In [ ]:
from sklearn.metrics import roc_auc_score

# Predict with y_test and pred_proba
roc_auc = roc_auc_score(y_test, pred_proba[:, 1])

print(f'ROC-AUC Score: {roc_auc}')

- Below is the **incorrect** way to calculate auc score:<br><br>

In [ ]:
# WRONG
roc_auc_wrong = roc_auc_score(y_test, pred)

print(f'Wrong ROC-AUC Score: {roc_auc_wrong}')

- This is what happens when you use the wrong one. The ROC-AUC score is wrong.
- ALWAYS use `predict_proba()` not `predict()` for the ROC-AUC
- Although very popular, the ROC-AUC is not perfect
    - For imbalanced classification with a severe skew and few examples of the minority class, the ROC AUC can be misleading.
    - This is because a small number of correct or incorrect predictions can result in a large change in the ROC Curve or ROC AUC score.
- A common alternative is the precision-recall curve and area under curve (PR-AUC).

<a id="summary"></a>
## Summary

1. [Roadmap](#recap)
    - We discussed concepts we learned in the last lesson
        - Supervised/Unsupervised Learning
        - Regression/Classification
        - Linear Regression
2. [Intro to Classification](#class)
    - Classification models seek to predict discrete possibilities (as opposed to continuous)
    - Intro to Logistic Regression
        - Seeks to classify "y" as either 0 class or 1 class
        - Business use-cases include qualifying leads, recommending products, predicting churn
        - Advantage is ease and speed of use, interpretability, and scalability
        - Logistic Regression uses a sigmoid function to create a *S*-looking line that goes from 0 to 1
        - Uses a decision boundary (threshold) where y = 0 if predicted probability < 0.5 and y = 1 if predicted probability > 0.5
3. [Customer Churn](#churn)
    - Used the Telco dataset to predict if customers would churn or not churn
    - [Exercise 1 (EDA)](#ex1)
        - Practiced EDA by finding the Value Counts and plotting Histograms
    - [Exercise 2 (Cleaning)](#ex2)
        - Practied encoding classes into 0 and 1 using `LabelEncoder()`
        - Manually encoded features into binary classes            
        - Practiced finding `nan` values that were encoded as blank "spaces"
    - [Feature Selection](#feat_sel)
        - Practiced feature selection via correlation plots
        - Used `pairplot()` to explore pairwise features and segregated colors based on class (churn and not churn)
    - [Exercise 3 (Train)](#ex3)
        - Performed `train_test_split`, training a `LogisticRegression` model, and finding the accuracy using `accuracy_score`
4. [Hyperparameters](#hyp_param)
    - Example of "knobs and dials"
    - Most ML algorithms have hyperparameters that a user has to optimize to maximize the model's output
5. [Evaluation Metrics](#eval)
    - [Confusion Matrix](#matrix)
        - 4 boxes that each hold vital pieces of information: TP, TN, FP, FN
    - [Data Imbalance](#imbalance)
        - Occurs when the target variable doesn't have an equal amount of samples for each class (0 and 1)
        - Often, it is the minority class that we're interested in studying
        - Example of imbalanced minority class is customer churn
    - [Classification Report](#class)
        - sklearn method that prints out the evaluation metrics from the confusion matrix
        - [Precision and Recall](#prec)
            - Precision is the number of true positives over all the samples that were predicted to be positive
            - Recall is the number of true positives over all the samples that were actually positive    
        - [F1 Score](#f1)
            - F1 score is the weighted mean of Precision and Recall
            - It's a good metric for scoring if both precision and recall are equally important when judging the model's performance
        - [Accuracy, Macro Avg, Weighted Avg](#acc)
            - Accuracy is the total number of correctly classified samples over all the samples
                - Misleading metric especially with imbalanced data
            - Macro Avg is the simple average of both class' Precision, Recall, and f1-score
            - Weighted avg is the same as Macro Avg except it tends to give more weight to the larger classes
            - Both Macro and Weighted averages are more used in multi-classification problems
        - [ROC-AUC](#rocauc)
            - Very popular metric amongst Data Scientists
            - Not biased towards either class
            - ROC is the curve and the derived AUC is the score
            - [Plot ROC](#roc)
                - It's a plot focused solely on Class 1
                - FPR Rate `(FP / (FP+TN))` plotted on the x-axis
                - TPR Rate aka Recall `(TP / (TP+FN))` plotted on the y-axis
                - Ideal point is the top left corner where 100% TPR and 0% Errors
                - Curve represents the tradeoff of higher TPR (Recall) vs increased errors with different thresholds
            - [AUC](#auc)
                - Metric that measures the area under the curve
                - Used to compare between models
        - [PR-AUC](#prauc)
            - Alternative to ROC-AUC
            - May be a better metric for certain imbalanced classification cases
            - Instead of False Positive Rate, it uses Precision on the x-axis
            - Plot shows the trade between Precision and Recall
            - Metric is unconcerned with the majority (negative) class
            - Ideal point would be towards the top right where Recall and Precision would both be 100%
6. [Improving the Score](#imp_score)
    - This section brainstormed ways to improve our models
    - Focus on Data Integrity:
        - Data Cleaning
        - Feature Selection
        - Feature Engineering
        - Scaling
    - Hyperameter Optimization
    - Try and compare different models
7. Below is a cheat sheet for Classification Evaluation Metrics:

<figure>
  <img src='img/Class_eval_cheat.png'/>
  <figcaption>Image from <a href='https://ai-ml-analytics.com/classification-metrics-in-machine-learning/'>Finxster</a></figcaption>
</figure>

<figure>
  <img src='img/log.jpg' width='40%'/>
</figure>

<a id="ref"></a>
## Additional Information

- [This playlist from Statquest](https://www.youtube.com/playlist?list=PLblh5JKOoLUKxzEP5HA2d-Li7IJkHfXSe) gives you a good overview of logistic regression
- Dataset:
    1. [Telco on Kaggle](https://www.kaggle.com/blastchar/telco-customer-churn)
- Logistic Regression:
    1. [Statquest! Logistic Regression](https://www.youtube.com/watch?v=yIYKR4sgzI8)
    2. [Linear vs Logistic Regression](https://www.javatpoint.com/linear-regression-vs-logistic-regression-in-machine-learning)
    3. [Logistic Regression](https://www.keboola.com/blog/logistic-regression-machine-learning)
    4. [Understanding Logistic Regression](https://towardsdatascience.com/understanding-logistic-regression-step-by-step-704a78be7e0a)
- Evaluation Metrics:
    1. [Sklearn Classification Report](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html)
    2. [Precision and Recall Made Simple](https://towardsdatascience.com/precision-and-recall-made-simple-afb5e098970f)
    3. [5 Evaluation Metrics all DS should know](https://towardsdatascience.com/the-5-classification-evaluation-metrics-you-must-know-aa97784ff226)
    4. [Classification Metrics in ML](https://ai-ml-analytics.com/classification-metrics-in-machine-learning/)
    5. [Top 10 Classification Eval Metrics](https://towardsdatascience.com/top-10-model-evaluation-metrics-for-classification-ml-models-a0a0f1d51b9)
    6. [Macro and Weighted Avg in Classification Report](https://datascience.stackexchange.com/questions/65839/macro-average-and-weighted-average-meaning-in-classification-report)
    7. [Micro, Macro, Weighted Ave of F1 Score](https://towardsdatascience.com/micro-macro-weighted-averages-of-f1-score-clearly-explained-b603420b292f#e273)
    8. [ROC and PR Curves for Imbalanced Classification](https://machinelearningmastery.com/roc-curves-and-precision-recall-curves-for-imbalanced-classification/)
- Class Imbalance:
    1. [Conf_Matrix Function](https://www.analyticsvidhya.com/blog/2020/10/improve-class-imbalance-class-weights/)
- [Bonus](https://www.youtube.com/watch?v=PWvfrTgaPBI)