# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy.random import randn

In [3]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [4]:
df

          W         X         Y         Z
A -0.228288 -0.607010  0.155750  0.288619
B -1.761849  0.200611  0.029698 -0.034792
C -1.228366  0.165949 -2.206289  1.196588
D -0.650531  1.614679 -1.386190 -0.540926
E  0.064297  1.144577 -0.946163  2.338362

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [5]:
df['W']

A   -0.228288
B   -1.761849
C   -1.228366
D   -0.650531
E    0.064297
Name: W, dtype: float64

In [6]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A -0.228288  0.288619
B -1.761849 -0.034792
C -1.228366  1.196588
D -0.650531 -0.540926
E  0.064297  2.338362

In [7]:
df.W

A   -0.228288
B   -1.761849
C   -1.228366
D   -0.650531
E    0.064297
Name: W, dtype: float64

DataFrame Columns are just Series

In [8]:
type(df['W'])

pandas.core.series.Series

**Creating a new column:**

In [9]:
df['new'] = df['W'] + df['Y']

In [10]:
df

          W         X         Y         Z       new
A -0.228288 -0.607010  0.155750  0.288619 -0.072538
B -1.761849  0.200611  0.029698 -0.034792 -1.732151
C -1.228366  0.165949 -2.206289  1.196588 -3.434655
D -0.650531  1.614679 -1.386190 -0.540926 -2.036721
E  0.064297  1.144577 -0.946163  2.338362 -0.881866

** Removing Columns**

In [11]:
df.drop('new',axis=1,inplace=True)

In [12]:
# Not inplace unless specified!
df

          W         X         Y         Z
A -0.228288 -0.607010  0.155750  0.288619
B -1.761849  0.200611  0.029698 -0.034792
C -1.228366  0.165949 -2.206289  1.196588
D -0.650531  1.614679 -1.386190 -0.540926
E  0.064297  1.144577 -0.946163  2.338362

In [13]:
df.drop('new',axis=1,inplace=True)

KeyError: ignored

In [ ]:
df

Can also drop rows this way:

In [14]:
df.drop('E')

          W         X         Y         Z
A -0.228288 -0.607010  0.155750  0.288619
B -1.761849  0.200611  0.029698 -0.034792
C -1.228366  0.165949 -2.206289  1.196588
D -0.650531  1.614679 -1.386190 -0.540926

** Selecting Rows**

In [15]:
df.loc['A']

W   -0.228288
X   -0.607010
Y    0.155750
Z    0.288619
Name: A, dtype: float64

Or select based off of position instead of label

In [16]:
df.iloc[2]

W   -1.228366
X    0.165949
Y   -2.206289
Z    1.196588
Name: C, dtype: float64

** Selecting subset of rows and columns **

In [17]:
df.loc['B','Y']

0.029698239615433792

In [18]:
df.loc[['A','B'],['W','Y']]

          W         Y
A -0.228288  0.155750
B -1.761849  0.029698

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [19]:
df

          W         X         Y         Z
A -0.228288 -0.607010  0.155750  0.288619
B -1.761849  0.200611  0.029698 -0.034792
C -1.228366  0.165949 -2.206289  1.196588
D -0.650531  1.614679 -1.386190 -0.540926
E  0.064297  1.144577 -0.946163  2.338362

In [20]:
df>0

       W      X      Y      Z
A  False  False   True   True
B  False   True   True  False
C  False   True  False   True
D  False   True  False  False
E   True   True  False   True

In [21]:
df[df>0]

          W         X         Y         Z
A       NaN       NaN  0.155750  0.288619
B       NaN  0.200611  0.029698       NaN
C       NaN  0.165949       NaN  1.196588
D       NaN  1.614679       NaN       NaN
E  0.064297  1.144577       NaN  2.338362

In [22]:
df[df['W']>0]

          W         X         Y         Z
E  0.064297  1.144577 -0.946163  2.338362

In [23]:
df[df['W']>0]['Y']

E   -0.946163
Name: Y, dtype: float64

In [24]:
df[df['W']>0][['Y','X']]

          Y         X
E -0.946163  1.144577

For two conditions you can use | and & with parenthesis:

In [25]:
df[(df['W']>0) & (df['Y'] > 1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [26]:
df

          W         X         Y         Z
A -0.228288 -0.607010  0.155750  0.288619
B -1.761849  0.200611  0.029698 -0.034792
C -1.228366  0.165949 -2.206289  1.196588
D -0.650531  1.614679 -1.386190 -0.540926
E  0.064297  1.144577 -0.946163  2.338362

In [27]:
newind = 'CA NY WY OR CO'.split()

In [28]:
df['States'] = newind

In [29]:
df

          W         X         Y         Z States
A -0.228288 -0.607010  0.155750  0.288619     CA
B -1.761849  0.200611  0.029698 -0.034792     NY
C -1.228366  0.165949 -2.206289  1.196588     WY
D -0.650531  1.614679 -1.386190 -0.540926     OR
E  0.064297  1.144577 -0.946163  2.338362     CO

In [30]:
df.set_index('States')

               W         X         Y         Z
States
CA     -0.228288 -0.607010  0.155750  0.288619
NY     -1.761849  0.200611  0.029698 -0.034792
WY     -1.228366  0.165949 -2.206289  1.196588
OR     -0.650531  1.614679 -1.386190 -0.540926
CO      0.064297  1.144577 -0.946163  2.338362

In [31]:
df

          W         X         Y         Z States
A -0.228288 -0.607010  0.155750  0.288619     CA
B -1.761849  0.200611  0.029698 -0.034792     NY
C -1.228366  0.165949 -2.206289  1.196588     WY
D -0.650531  1.614679 -1.386190 -0.540926     OR
E  0.064297  1.144577 -0.946163  2.338362     CO

In [32]:
df.set_index('States',inplace=True)

In [33]:
df

               W         X         Y         Z
States
CA     -0.228288 -0.607010  0.155750  0.288619
NY     -1.761849  0.200611  0.029698 -0.034792
WY     -1.228366  0.165949 -2.206289  1.196588
OR     -0.650531  1.614679 -1.386190 -0.540926
CO      0.064297  1.144577 -0.946163  2.338362