# Data Input and Output

This notebook is the reference code for getting input and output, pandas can read a variety of file types using its pd.read_ methods. Let's take a look at the most common data types:

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Excel_Sample.xlsx to Excel_Sample.xlsx

In [3]:
import numpy as np
import pandas as pd
import sys

In [4]:
!ls

drive  Excel_Sample.xlsx  sample_data

## CSV

### CSV Input

In [5]:
df = pd.read_excel('Excel_Sample.xlsx')
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

### CSV Output

In [7]:
df.to_csv('example',index=False)

## Excel
Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash.

In [8]:
!pip install xlrd
!pip install openpyxl

Requirement already satisfied: xlrd in /usr/local/lib/python3.6/dist-packages (1.1.0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.6/dist-packages (2.5.9)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.6/dist-packages (from openpyxl) (1.0.1)
Requirement already satisfied: jdcal in /usr/local/lib/python3.6/dist-packages (from openpyxl) (1.4.1)

### Excel Input

In [10]:
pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

### Excel Output

In [12]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')