In [0]:
import pandas as pd
import numpy as np

In [0]:
index = pd.DataFrame([('one', 'a'), ('one', 'b'), ('two', 'a'), ('two', 'b')])

In [0]:
index

     0  1
0  one  a
1  one  b
2  two  a
3  two  b

In [0]:
index.stack()

0  0    one
   1      a
1  0    one
   1      b
2  0    two
   1      a
3  0    two
   1      b
dtype: object

In [0]:
index.unstack()

0  0    one
   1    one
   2    two
   3    two
1  0      a
   1      b
   2      a
   3      b
dtype: object

In [0]:
# Row Multi-Index
row_idx_arr = list(zip(['r0', 'r0'], ['r-00', 'r-01']))
row_idx = pd.MultiIndex.from_tuples(row_idx_arr)

# Column Multi-Index
col_idx_arr = list(zip(['c0', 'c0', 'c1'], ['c-00', 'c-01', 'c-10']))
col_idx = pd.MultiIndex.from_tuples(col_idx_arr)

# Create the DataFrame
d = pd.DataFrame(np.arange(6).reshape(2,3), index=row_idx, columns=col_idx)
#d = d.applymap(lambda x: (x // 3, x % 3))

In [0]:
d

          c0        c1
        c-00 c-01 c-10
r0 r-00    0    1    2
   r-01    3    4    5

In [0]:
# Stack/Unstack
s = d.stack()
u = d.unstack()

In [0]:
s

               c0   c1
r0 r-00 c-00  0.0  NaN
        c-01  1.0  NaN
        c-10  NaN  2.0
   r-01 c-00  3.0  NaN
        c-01  4.0  NaN
        c-10  NaN  5.0

In [0]:
u

     c0                  c1
   c-00      c-01      c-10
   r-00 r-01 r-00 r-01 r-00 r-01
r0    0    3    1    4    2    5

In [0]:
# Row Multi-Index
row_idx_arr = list(zip(['r0', 'r0']))
row_idx = pd.MultiIndex.from_tuples(row_idx_arr)

# Column Multi-Index
col_idx_arr = list(zip(['c0', 'c0', 'c1']))
col_idx = pd.MultiIndex.from_tuples(col_idx_arr)

# Create the DataFrame
d = pd.DataFrame(np.arange(6).reshape(2,3), index=row_idx, columns=col_idx)
#d = d.applymap(lambda x: (x // 3, x % 3))

In [0]:
d

    c0  c0  c1
r0   0   1   2
r0   3   4   5

In [0]:
# Stack/Unstack
s = d.stack()
u = d.unstack()

In [0]:
s

r0  c0    0
    c0    1
    c1    2
    c0    3
    c0    4
    c1    5
dtype: int32

In [0]:
u

c0  r0    0
    r0    3
    r0    1
    r0    4
c1  r0    2
    r0    5
dtype: int32